version: '3'
services:
  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password # for demo purpose DO NOT LEAVE YOUR PLAINTEXT PASSWORD HERE
